# Generated by Django 5.0.7 on 2024-08-03 10:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_verified', models.BooleanField(default=False)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BillingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_address', models.CharField(blank=True, default='street_address', max_length=255, null=True)),
                ('city', models.CharField(blank=True, default='city', max_length=100, null=True)),
                ('state', models.CharField(blank=True, default='state', max_length=100, null=True)),
                ('postal_code', models.CharField(blank=True, default='postal_code', max_length=20, null=True)),
                ('country', models.CharField(blank=True, default='country', max_length=100, null=True)),
                ('number', models.CharField(blank=True, default='number', max_length=25, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_address', models.CharField(blank=True, default='street_address', max_length=255, null=True)),
                ('city', models.CharField(blank=True, default='city', max_length=100, null=True)),
                ('state', models.CharField(blank=True, default='state', max_length=100, null=True)),
                ('postal_code', models.CharField(blank=True, default='postal_code', max_length=20, null=True)),
                ('country', models.CharField(blank=True, default='country', max_length=100, null=True)),
                ('number', models.CharField(blank=True, default='number', max_length=25, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
