# Generated by Django 5.0.7 on 2024-08-03 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account_Dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='profile_image/'),
        ),
        migrations.AlterField(
            model_name='account',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='city',
            field=models.CharField(blank=True, default='Dhaka', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='country',
            field=models.CharField(blank=True, default='Bangladesh', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='number',
            field=models.CharField(blank=True, default='+8801234567890', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='postal_code',
            field=models.CharField(blank=True, default='1212', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='state',
            field=models.CharField(blank=True, default='Dhaka Division', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='street_address',
            field=models.CharField(blank=True, default='123 Example Street', max_length=255, null=True),
        ),
    ]
