# Generated by Django 5.0.7 on 2024-08-10 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_Checkout', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
    ]
