# Generated by Django 5.0.7 on 2024-08-02 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='num_reviews',
            new_name='total_reviews',
        ),
        migrations.RemoveField(
            model_name='product',
            name='show_rating',
        ),
    ]
