# Generated by Django 5.0.7 on 2024-08-02 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0002_rename_num_reviews_product_total_reviews_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='new_price',
        ),
    ]
